Feature/create candidate model
UdL-EPS-SoftArch/AcademicRecruitAPI-GEIADE pull request #28
Opened 2021-03-16 16:05 UTC by polgodia

Created Candidate Model and Tested Creation and Update

2021-03-16 19:15 UTC, rogargon requested changes

2021-03-16 19:15 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/domain/CandidateTest.java
> +class CandidateTest {
This class doesn't seem necessary, specially to test methods that are actually generated by external code (Lombok)

2021-03-16 19:15 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/UpdateCandidateStepDefs.java
> +        candidate.setId(Long.valueOf(id));
No need to set the ID if it is autogenerated by the persistence layer (database)

2021-03-16 19:15 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/UpdateCandidateStepDefs.java
> +        newResourceUri = "/candidates/"+ id;
To generate the final ID, the CandidateRepository should be used to save the new instance. The return value is the persisted candidate with the final ID. You can then use getUri()

2021-03-16 19:15 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/UpdateCandidateStepDefs.java
> +        stepDefs.result = stepDefs.mockMvc.perform(
You should create the existing candidate in a separate step (Given there is a candidate with name "oldname"...) and then update the name with a different one in this step

2021-03-16 19:15 UTC, rogargon commented on src/test/resources/features/UpdateCandidate.feature
> +    When I change the name of the candidate with id "1" to "lluc"
Better not to used fixed IDs in the steps

2021-03-16 19:15 UTC, rogargon commented on src/test/resources/features/DeleteCandidate.feature
> +    Then The response code is 201
201 (CREATED) is not the expected outcome when deleting a resource

2021-03-19 18:52 UTC, bergacat1 approved these changes

2021-03-19 18:54 UTC, merged