Feature/delete candidate model
UdL-EPS-SoftArch/AcademicRecruitAPI-GEIADE pull request #29
Opened 2021-03-17 17:28 UTC by polgodia

CRUD Delete Candidate

2021-03-17 18:13 UTC, rogargon requested changes

2021-03-17 18:13 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/DeleteCandidateStepDefs.java
> +        Candidate candidate = new Candidate();
It is better to create the candidate in a separate @Given step like `There exist a candidate with name...` and then here recover the candidate using a findByName and then its URI using the .getUri() method

2021-03-17 18:13 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/DeleteCandidateStepDefs.java
> +    @And("The previously deleted candidate doesn't exist")
This step recovers the recently created candidate but doesn't check if it exists or not. Better to directly check using the findByName method of the repository and then assert that the returned list is empty. The step would be something like @Then `There is no candidate with name...`

2021-03-17 18:13 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/UpdateCandidateStepDefs.java
> +        Candidate candidate = new Candidate();
Like in the case of Delete (in fact you can reuse the step and its definition) use a separate step to state that there is an existing candidate with given name. Then, this step should just update the name for that candidate. You can recover it using its current name provided in the step, like @When `I change the name of the candidate with name ... to ...`

2021-03-17 18:13 UTC, rogargon commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/UpdateCandidateStepDefs.java
> +    public void thePreviouslyUpdatedCandidateHasNowName(String name) throws Throwable {
You can check, reusing existing step, that there is no candidate with the old name and that there is a candidate with the new one. In both cases, you can use a findByName, no need to go through the API in the @Given and @Then steps

2021-03-17 18:13 UTC, rogargon commented on src/test/resources/features/DeleteCandidate.feature
> +Feature: Candidate Delte
Candidate Delete

2021-03-23 15:26 UTC, bergacat1 approved these changes

2021-03-23 15:26 UTC, merged