Feature/relationships selection process process stage
UdL-EPS-SoftArch/AcademicRecruitAPI-GEIADE pull request #40
Opened 2021-03-24 17:20 UTC by ivancolomer

Added OneToMany and OneToOne relatioships between selectionProcess and processStage

2021-03-24 17:48 UTC, bergacat1 requested changes

2021-03-24 17:48 UTC, bergacat1 commented on src/main/java/cat/udl/eps/softarch/academicrecruit/domain/ProcessStage.java
> +    private SelectionProcess selectionProcessBeingActive;
Remember we said we would only set the relation on the dominating side of the relation. You should remove the relation from this side.

2021-03-24 17:48 UTC, bergacat1 commented on src/main/java/cat/udl/eps/softarch/academicrecruit/domain/SelectionProcess.java
> +    private List<ProcessStage> processStages;
Same here, you should remove the relation from this side.

2021-03-24 18:00 UTC, bergacat1 requested changes, later dismissed

2021-03-24 18:00 UTC, bergacat1 commented on src/test/java/cat/udl/eps/softarch/academicrecruit/steps/UpdateProcessStageStepDefs.java
> +    @Transactional
Not necessary now

2021-03-25 14:11 UTC, rogargon commented
@paulavicente @ivancolomer Do not forget to address the last comment from Albert so this PR can be accepted

2021-03-25 14:28 UTC, rogargon approved these changes

2021-03-25 14:28 UTC, merged